### ISSUE TITLE
add two more links to loans and lenders bar, call them tools and graphs

### ISSUE THREAD

**Issue by ericaltshuler** [lorenzotan/streamline-broker#8]

**Comment by lorenzotan** [comment]
Also add "Brokers" placeholder

**Comment by lorenzotan** [comment]
ltan@[master]:~/Sites/streamline-broker/broker1/inputs$ git push origin master
Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (7/7), 685 bytes | 685.00 KiB/s, done.
Total 7 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/lorenzotan/streamline-broker.git
   abd4fd8..2d568e4  master -> master
